"""Deterministic product-facing assessment and evidence reports."""

from .errors import (
    AssessmentCompatibilityError,
    AssessmentPolicyLoadError,
    AssessmentPolicySpecError,
    AssessmentResultLoadError,
    AssessmentResultSpecError,
    AssuranceReportError,
)
from .policy import (
    POLICY_SCHEMA_VERSION,
    AssessmentCriteria,
    AssessmentPolicy,
    CaseAssessmentOverride,
    CaseRequirement,
    CriteriaOverride,
    assessment_policy_from_dict,
    load_assessment_policy,
    loads_assessment_policy,
    validate_assessment_policy,
)
from .report import (
    ERROR_SCHEMA_VERSION,
    EVIDENCE_BOUNDARY,
    REPORT_SCHEMA_VERSION,
    AssuranceReport,
    assess_controller,
    assess_fault_suite_result,
    fault_suite_result_from_dict,
    load_fault_suite_result,
    loads_fault_suite_result,
    render_report_json,
    render_report_markdown,
    write_assurance_report,
)

__all__ = [
    "ERROR_SCHEMA_VERSION",
    "EVIDENCE_BOUNDARY",
    "POLICY_SCHEMA_VERSION",
    "REPORT_SCHEMA_VERSION",
    "AssessmentCompatibilityError",
    "AssessmentCriteria",
    "AssessmentPolicy",
    "AssessmentPolicyLoadError",
    "AssessmentPolicySpecError",
    "AssessmentResultLoadError",
    "AssessmentResultSpecError",
    "AssuranceReport",
    "AssuranceReportError",
    "CaseAssessmentOverride",
    "CaseRequirement",
    "CriteriaOverride",
    "assess_controller",
    "assess_fault_suite_result",
    "assessment_policy_from_dict",
    "fault_suite_result_from_dict",
    "load_assessment_policy",
    "load_fault_suite_result",
    "loads_assessment_policy",
    "loads_fault_suite_result",
    "render_report_json",
    "render_report_markdown",
    "validate_assessment_policy",
    "write_assurance_report",
]
